project/authentication/urls.py
from django.urls import path

from .views import sing_up, log_in, log_out, check

app_name="authentication"

urlpatterns = [
    path('register/', sing_up ,name='register'),
    path('log-in/', log_in,name='login'),
    path('log-out/', log_out,name='logout'),
    path('check/', check,name='check'),
]

project/book/urls.py
from django.contrib import admin
from django.contrib.auth import authenticate
from django.urls import path, include
from .main_ import home, book_info, shop_list_, list_book, my_book, pin, profile, check, shop, search, stream
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home, name='home'),
    path('user/', include('authentication.urls')),
    path('book/<pk>/<name>/', book_info),
    path('book/list/<name_group>/<sort>/', list_book),
    path('book/shoping-list/', shop_list_, name='list'),
    path('book/my-book/', my_book, name='my-book'),
    path('book/pin/', pin, name='pin'),
    path('book/shop/', shop, name='shop'),
    path('profile/check-email/', check),
    path('user/profile/', profile, name='profile'),
    path('book/search/', search, name='search'),
    path('stream/', stream, name='stream'),
    path('rest/', include('_rest_.urls')),
]

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/templates/card.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'font/font-awesome/css/font-awesome.min.css' %}">

    <title>book</title>
    <style>
        @font-face {
            font-family: Vazir;
            font-style: normal;
            font-weight: normal;
            src: url('{% static "font/fonts/Vazir.eot" %}');
            src: url('{% static "font/fonts/Vazir.eot?#iefix" %}') format('embedded-opentype'),
            url('{% static "font/fonts/Vazir.woff2" %}') format('woff2'),
            url('{% static "font/fonts/Vazir.woff" %}') format('woff'),
            url('{% static "font/fonts/Vazir.ttf" %}') format('truetype');
        }

        body {
            background: #F0F3F5;
            font-family: Vazir;
            transition: 1s;
        }

        .card-body {
            position: absolute;
            top: 0;
            display: none;
            transition: 1s;
            padding: 2px;
            border-radius: 15px;
            z-index: 1;
            background-color: rgba(255, 255, 255, 0.5);
            width: 100%;
            height: 100%;
        }

        .card:hover .card-body {
            display: block;
            transition: 1s;
        }

        .card:hover {
            box-shadow: 5px 5px 50px 5px #fdc800;
            width: 110%;
            margin-right: -5%;
        }

        .card {
            max-width: 450px;
            border: 5px solid #fdc800;
            text-align: center;
            transition: 1s;
            border-radius: 10px;
            padding: 0;
            background-color: transparent;
            margin-top: 10px;
            box-shadow: 1px 5px 18px 4px #000000;
        }

        .card2 {
            max-width: 450px;
            border: 5px solid #fdc800;
            text-align: center;
            transition: 1s;
            border-radius: 10px;
            padding: 0;
            background-color: transparent;
            margin-top: 10px;
            box-shadow: 1px 5px 18px 4px #000000;
        }

        .card img {
            position: relative;
            width: 100%;
        }

        img {
            max-width: 250px;
            border-radius: 5px;
        }

        

        @media screen and (min-width: 200px) {
            .card-columns {
                column-count: 3;
                column-fill: auto;
                transition: 1s;
            }

            .card-body-text {
                font-size: 5px;
                padding: 1px;
            }

            .card-body-text-titile {
                font-size: 7px;
            }

            .tab {
                display: none;
            }

            #book-name {
                font-size: 15px;
            }

            .book-detail {
                font-size: 7px;
            }

        }

        @media screen and (min-width: 576px) {
            .card-columns {
                column-count: 4;
                column-fill: auto;
                transition: 1s;
            }

            #book-name {
                font-size: 18px;
            }

            .book-detail {
                font-size: 13px;
            }

        }

        @media screen and (min-width: 768) {
            .book-detail {
                font-size: 15px;
            }

        }

        @media screen and (min-width: 929px) {
            .card-columns {
                column-count: 6;
                column-fill: auto;
                transition: 1s;
            }

            .tab {
                display: block;
            }

            #book-name {
                font-size: 30px;
            }

            .book-detail {
                font-size: 15px;
            }

        }

        .amir_table2 {
            display: none;
            transition: 1s;
            border-radius: 5px;
        }

        .amir_table {
            color: #44244c;
            transition: 1s;
            width: 100%;

        }

        .amir_table :hover {
            background-color: #44244c;
            transition: 1s;
        }

        .amir_table:hover .amir_table2 {
            display: block;
            border-radius: 5px;
            transition: 0.5s;
        }

        .image_show_main {
            box-shadow: 5px 5px 50px 5px #000000;
        }

        /* width */
        ::-webkit-scrollbar {
            width: 10px;
        }

        /* Track */
        ::-webkit-scrollbar-track {
            background: #f1f1f1;
        }

        /* Handle */
        ::-webkit-scrollbar-thumb {
            background: #888;
        }

        /* Handle on hover */
        ::-webkit-scrollbar-thumb:hover {
            background: #555;
        }

        .dropdown .dropdown-menu {
            display: none;
        }

        .dropdown:hover .dropdown-menu {
            display: block;
        }

        .dropdown-menu {
            width: 100%;
            text-align: right;
        }

        #book-name {
            text-align: right;
            color: #44244c;
        }

        .book-detail {
            margin: 0;
            padding: 0;
        }

        .nav {
            position: sticky;
            top: 0;
            z-index: 3;
        }
    </style>
</head>


<body>

    {% include 'component/nav2.html' %}

    <div class="alert alert-warning" role="alert">
        {% for i in data %}

            {% if forloop.counter > 1 %}

                {% else %}
                    {% if 'ارزان ترین' in request.path %}
                        <h1 id="book-name">کتاب های {{ i.grouping }}-ارزان ترین ها</h1>
                    {% endif %}
                    {% if 'تازه ها' in request.path %}
                        <h1 id="book-name">کتاب های {{ i.grouping }}-تازه ها</h1>
                    {% endif %}
                    {% if 'پربحث ترین' in request.path %}
                        <h1 id="book-name">کتاب های {{ i.grouping }}-پربحث ترین ها</h1>
                    {% endif %}
                    {% if 'پرفروش ترین' in request.path %}
                        <h1 id="book-name">کتاب های {{ i.grouping }}-پرفروش ترین ها</h1>
                    {% endif %}

            {% endif %}

        {% endfor %}

    </div>

    <div class="container-fluid" style="margin-top: 50px;">
        <div class="row">
            
            {% include 'component/table3-list.html' %}

            <div class="col-lg-9 col-12 mr-auto ml-auto overflow-auto image_show_main"
                style="background-color: #fdc800; width: 99%; max-height: 520px; min-height: 500px;">
                
                
                {% if list != False %}
                <div style="background-color: rebeccapurple; border-radius: 5px; position: sticky; top: 0; z-index: 2;">
                    <div class="dropdown" style="width: 100%; border-radius: 5px;">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" style="width: 100%; border-radius: 5px;" aria-expanded="false">
                            چینش بر اساس
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            {% for i in data %}

                                {% if forloop.counter > 1 %}
                                
                                {% else %}
                                    <li><a class="dropdown-item"
                                            href="http://127.0.0.1:8888/book/list/{{ i.grouping }}/تازه‌ها/">تازه‌ها</a></li>
                                    <li><a class="dropdown-item"
                                            href="http://127.0.0.1:8888/book/list/{{ i.grouping }}/ارزان ترین/">ارزان ترین</a>
                                    </li>
                                    <li><a class="dropdown-item"
                                            href="http://127.0.0.1:8888/book/list/{{ i.grouping }}/پربحث ترین/">پربحث ترین</a>
                                    </li>
                                    <li><a class="dropdown-item"
                                            href="http://127.0.0.1:8888/book/list/{{ i.grouping }}/پرفروش ترین/">پرفروش ترین</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% endif %}
                    
                
                <div class="card-columns ">


                    {% for i in data %}
                    <a href="http://127.0.0.1:8888/book/{{ i.id }}/{{ i.name }}">

                        <div class="card card2">
                            <img src="{{ i.image.url }}" alt="">
                            <div class="card-body">
                                <p class="book-detail" style="color: green;">نام کتاب: {{ i.name }}</p>
                                <p class="book-detail" style="color: blue;">نویسنده: {{ i.author }}</p>
                                <p class="book-detail" style="color: red;">مترجم : {{ i.tranlator }}</p>
                                <p class="book-detail" style="color: orange;">ناشر: {{ i.publisher }}</p>
                                <p class="book-detail" style="color: greenyellow;">قیمت {{ i.price }} تومان</p>
                            </div>
                        </div>
                    </a>
                    {% endfor %}

                </div>
            </div>
        </div>
        <dir class="row mr-auto ml-auto" style="padding: 0;">
            <div class="col-12" style="background-color: #fdc800; height: 500px; border-radius: 5px;">f
            </div>
        </dir>
    </div>
</body>

</html>

project/templates/check.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>check</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/check.css' %}">
    <style>
        @font-face {
            font-family: Vazir;
            font-style: normal;
            font-weight: normal;
            src: url('{% static "font/fonts/Vazir.eot" %}');
            src: url('{% static "font/fonts/Vazir.eot?#iefix" %}') format('embedded-opentype'),
            url('{% static "font/fonts/Vazir.woff2" %}') format('woff2'),
            url('{% static "font/fonts/Vazir.woff" %}') format('woff'),
            url('{% static "font/fonts/Vazir.ttf" %}') format('truetype');
        }

        body {
            font-family: Vazir;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-12" style="padding: 0;">
                <div class="d-flex flex-wrap">
                    <h2 style="color: blue; text-align: center" dir="rtl">{{ error }}</h2>
                    <div class="col-12" id="main_">
                        <img src="{% static 'image/Newsletter.png' %}" id="image_">
                        <div class="col-12" id="main__">
                            <form>
                                {% csrf_token %}
                                <input type="password" name="__pass__"
                                    placeholder="enter pass how sending to your email now">
                                <div class="col-5 mr-auto ml-auto" id="main___">
                                    <button type="submit" formmethod="post">Check</button>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div id="help" style="font-family: Vazir;">
                        <h1 dir="rtl">راهنمایی:</h1>
                        <p dir="rtl">رمزی که برای شما درون ایمیل شما ارسال شده است را وارد کنید اگر اشتباه وارد شود باید
                            کل مرحله ثبت
                            نام را از اول طی کنید</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

project/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>
    {% csrf_token %}
    <!-- Icons font CSS-->
    <link href="{% static 'register/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'register/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <!-- Vendor CSS-->
    <link href="{% static 'register/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'register/vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'register/css/main.css' %}" rel="stylesheet" media="all">

    <style>
        @font-face {
            font-family: Vazir;
            font-style: normal;
            font-weight: normal;
            src: url('{% static "font/fonts/Vazir.eot" %}');
            src: url('{% static "font/fonts/Vazir.eot?#iefix" %}') format('embedded-opentype'),
            url('{% static "font/fonts/Vazir.woff2" %}') format('woff2'),
            url('{% static "font/fonts/Vazir.woff" %}') format('woff'),
            url('{% static "font/fonts/Vazir.ttf" %}') format('truetype');
        }
        body{
            font-family: Vazir;
        }
    </style>
</head>

<body>
    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
                    <h2 class="title">ورود</h2>
                    {% csrf_token %}
                    <form >
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    {% csrf_token %}
                                    <label class="label">شماره همراه یا ایمیل</label>
                                    <input class="input--style-4" type="text" name="_phone_" required>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">پسورد</label>
                                    <input class="input--style-4" type="password" name="_pass1_" required>
                                </div>
                            </div>
                        <div class="p-t-15">
                            {% csrf_token %}
                            <button class="btn btn--radius-2 btn--blue" type="submit" formmethod="POST">وارد شوید</button>
                        </div>
                    </form>
                    <a href="{% url 'authentication:register' %}"><button style="margin: auto;"
                        class="btn btn">ساخت حساب</button></a>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static 'register/vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'register/vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'register/vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'register/vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'register/js/global.js' %}"></script>

</body>

</html>
<!-- end document-->

project/templates/mark-book.html
{% extends 'component/user.html' %}


{% block main %}

<div class="alert alert-warning" role="alert">
    <h1>کتاب های نشان شده</h1>
</div>

{% for i in data  %}
<div class="card mb-3" style="max-width: 540px; float: {% cycle 'right' 'left' %}; direction: {% cycle 'rtl' 'ltr' %};">
    <div class="row no-gutters">
        <div class="col-md-4 col-5">
            <a href="http://127.0.0.1:8888/book/{{ i.id }}/{{ i.name }}">
                <img src="{{ i.image.url }}" class="card-img" alt="رفتن به کتاب {{ i.name }}">
            </a>
        </div>
        <div class="col-md-8 col-7">
            <div class="card-body">
                <h5 class="card-title">{{ i.name }}</h5>
                <p class="card-text">{{ i.description|truncatechars:128 }}</p>
                <a href="#"><button type="button" class="btn btn-outline-warning">مشاهده کتاب</button></a>
                <form action="http://127.0.0.1:8888/book/pin/" method="POST">
                    {% csrf_token %}
                    <input type="text" style="display: none;" value="{{ i.id }}" name="id">
                    <input type="text" style="display: none;" value="{{ i.name }}" name="name">
                    <input type="text" style="display: none;" value="yes" name="delete">
                    <input type="text" style="display: none;" value="{{ user.email }}" name="email">
                    <button type="submit" class="pin btn btn-outline-danger"><i class="fa fa-trash" aria-hidden="true"></i>حذف کتاب</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock main %}

project/templates/profile-edit.html
{% extends 'component/user.html' %}


{% block main %}

<div class="alert alert-warning" role="alert">
    <h1 style="color: green;">{{ message }}</h1>
</div>

<ul class="list-group" style="padding: 0;">
    <li class="list-group-item list1">نام و نام خانوادگی<i class="fa fa-chevron-down" aria-hidden="true"></i>
        <ul class="list-body">
            <section class="get-in-touch">
                <form class="contact-form row" action="{% url 'profile' %}">
                    {% csrf_token %}
                    <div class="form-field col-lg-6">
                        <input id="name" class="input-text js-input" value="{{ data.name }}" name="name" type="text" required>
                        <label class="label" for="name">نام</label>
                    </div>
                    <div class="form-field col-lg-6">
                        <input id="name" class="input-text js-input" value="{{ data.lastname }}" name="lastname" type="text" required>
                        <label class="label" for="name">نام خانوادگی</label>
                    </div>
                    <div class="form-field col-lg-12">
                        <input class="submit-btn" type="submit" value="ویرایش" formmethod="POST">
                    </div>
                </form>
            </section>
        </ul>
    </li>
    <li class="list-group-item list1">ایمیل<i class="fa fa-chevron-down" aria-hidden="true"></i>
        <ul class="list-body">
            <section class="get-in-touch mr-auto ml-auto">
                <form class="contact-form row" action="{% url 'profile' %}">
                    {% csrf_token %}
                    <div class="form-field col-lg-6 mr-auto ml-auto">
                        <input id="name" style="text-align: left;" class="input-text js-input" name="email" value="{{ data.email }}"
                            type="text" required>
                        <label class="label" for="name">ایمیل</label>
                    </div>
                    <div class="form-field col-lg-6 mr-auto ml-auto">
                        <input class="submit-btn" type="submit" value="ویرایش" formmethod="POST">
                    </div>
                </form>
            </section>
        </ul>
    </li>
    <li class="list-group-item list1">شماره<i class="fa fa-chevron-down" aria-hidden="true"></i>
        <ul class="list-body">
            <section class="get-in-touch mr-auto ml-auto">
                <form class="contact-form row">
                    {% csrf_token %}
                    <div class="form-field col-lg-6 mr-auto ml-auto">
                        <input id="name" class="input-text js-input" value="{{ data.phone }}" name="phone" type="text" required>
                        <label class="label" for="name">شماره</label>
                    </div>
                    <div class="form-field col-lg-6 mr-auto ml-auto">
                        <input class="submit-btn" type="submit" value="ویرایش" formmethod="POST">
                    </div>
                </form>
            </section>
        </ul>
    </li>
    <li class="list-group-item list1">پسورد<i class="fa fa-chevron-down" aria-hidden="true"></i>
        <ul class="list-body">
            <section class="get-in-touch mr-auto ml-auto">
                <form class="contact-form row">
                    {% csrf_token %}
                    <div class="form-field col-lg-6 mr-auto ml-auto">
                        <input id="name" class="input-text js-input" type="text" name="pass1" required>
                        <label class="label" for="name">پسورد جدید</label>
                    </div>
                    <div class="form-field col-lg-6 mr-auto ml-auto">
                        <input id="name" class="input-text js-input" type="text" name="pass-now" required>
                        <label class="label" for="name">پسورد فعلی</label>
                    </div>
                    <div class="form-field col-lg-6 mr-auto ml-auto">
                        <input id="name" class="input-text js-input" type="text" name="pass2" required>
                        <label class="label" for="name">تکرار پسورد جدید</label>
                    </div>
                    <div class="form-field col-lg-6 mr-auto ml-auto">
                        <input class="submit-btn" type="submit" value="ویرایش" formmethod="POST">
                    </div>
                </form>
            </section>
        </ul>
    </li>
</ul>

{% endblock main %}

project/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>
    {% csrf_token %}
    <!-- Icons font CSS-->


    <link href="{% static 'register/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet"
        media="all">
    <link href="{% static 'register/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->

    <!-- Vendor CSS-->
    <link href="{% static 'register/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'register/vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'register/css/main.css' %}" rel="stylesheet" media="all">

    <style>
        @font-face {
            font-family: Vazir;
            font-style: normal;
            font-weight: normal;
            src: url('{% static "font/fonts/Vazir.eot" %}');
            src: url('{% static "font/fonts/Vazir.eot?#iefix" %}') format('embedded-opentype'),
            url('{% static "font/fonts/Vazir.woff2" %}') format('woff2'),
            url('{% static "font/fonts/Vazir.woff" %}') format('woff'),
            url('{% static "font/fonts/Vazir.ttf" %}') format('truetype');
        }

        body {
            font-family: Vazir;
        }

        label{
            font-family: Vazir;
        }
        input{
            font-family: Vazir;
        }
        input:focus{
            background-color: #ffe399;
            color: #44244c;
            animation-name: amir2;
            animation-duration: 1s;
            animation-iteration-count: 100;
        }

        @keyframes amir2 {
            25% {
                border-radius: 25px;
            }

            50% {
                border-radius: 60px;
            }

            75% {
                border-radius: 80px;
            }

            100% {
                border-radius: 0px;
            }
        }

        h2{
            font-family: Vazir;
        }
        button{
            font-family: Vazir;
            padding: 0;
        }
        .input-group{
            box-shadow: 5px 5px 10px #44244c;
            border-radius: 20px 20px 0px 0px ; 
            padding: 2px;
        }
    </style>
</head>

<body>
    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
        <div class="wrapper wrapper--w680">
            <div class="card card-4" style="background-color: #fdc800;">
                <div class="card-body">
                    <h3 style="font-family: Vazir; color: rebeccapurple; text-align: center;">{{error }}</h3>
                    <br>
                    <h2 class="title">ساخت حساب</h2>
                    {% csrf_token %}
                    <form>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">نام</label>
                                    <input class="input--style-4" type="text" name="_name_" value="{{name}}" required>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">نام خانوادگی</label>
                                    <input class="input--style-4" type="text" name="_lastname_" value="{{lastname}}" required>
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">ایمیل</label>
                                    <input class="input--style-4" type="email" name="_email_" value="{{email}}" required>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">شماره همراه</label>
                                    <input class="input--style-4" type="text" name="_phone_" value="{{phone}}" required>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">پسورد</label>
                                    <input class="input--style-4" type="password" name="_pass1_" required>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">تکرار پسورد</label>
                                    <input class="input--style-4" type="password" name="_pass2_" required>
                                </div>
                            </div>
                        </div>

                        <div class="p-t-15">
                            {% csrf_token %}
                            <button class="btn btn--radius-2 btn--blue" type="submit" formmethod="POST">ساخت
                                حساب</button>
                    </form>
                    <a href="{% url 'authentication:login' %}"><button style="margin: auto;"
                            class="btn btn--radius-2 btn--blue">ورود به حساب قبلی</button></a>
                </div>
            </div>
        </div>
    </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static 'register/vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'register/vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'register/vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'register/vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'register/js/global.js' %}"></script>

</body>

</html>
<!-- end document-->

project/templates/search.html
{% extends 'component/card.html' %}