project/authentication/urls.py
from django.urls import path

from .views import sing_up, log_in, log_out, check

app_name="authentication"

urlpatterns = [
    path('register/', sing_up ,name='register'),
    path('log-in/', log_in,name='login'),
    path('log-out/', log_out,name='logout'),
    path('check/', check,name='check'),
]

project/book/urls.py
from django.contrib import admin
from django.contrib.auth import authenticate
from django.urls import path, include
from .main_ import home, book_info, shop_list_, list_book, my_book, pin, profile, check, shop, search, stream
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home, name='home'),
    path('user/', include('authentication.urls')),
    path('book/<pk>/<name>/', book_info),
    path('book/list/<name_group>/<sort>/', list_book),
    path('book/shoping-list/', shop_list_, name='list'),
    path('book/my-book/', my_book, name='my-book'),
    path('book/pin/', pin, name='pin'),
    path('book/shop/', shop, name='shop'),
    path('profile/check-email/', check),
    path('user/profile/', profile, name='profile'),
    path('book/search/', search, name='search'),
    path('stream/', stream, name='stream'),
    path('rest/', include('_rest_.urls')),
]

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/templates/component/best_book.html
<!-- بهترین کتاب-->
{% load static %}

{% for  i in top %}
    {% if forloop.counter <= 1 %}
      

  <div class="col-lg-9" >
      <div class="accordion" id="accordionExample">
        <div class="accordion-item mb-5 border border-x-0 border-bottom-0 border-200">
          <div class="accordion-header" id="heading1">
            <div class="accordion-button" role="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="true" aria-controls="collapse1">
              <div class="row w-100 justify-content-center">
                <div class="col-sm-6 font-base"><span class="mb-0 fw-bold text-start fs-1 text-1200" style="direction: rtl; text-align: center;"><a href="http://127.0.0.1:8888/book/{{i.id}}/{{i.name}}/">{{ i.name }}</a></span>
                  <p class="my-2">{{ i.author }}</p>
                </div>
                <div class="col-8 col-sm-4">
                  
                  {% if i.average == 1 %}
                  <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                  </svg>
                  {% endif %}
                  
                  {% if i.average == 2 %}
                  <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                  </svg>
                  <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                  </svg>
                  {% endif %}
                  
                  {% if i.average == 3 %}
                    <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                      <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                    </svg>
                    <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                      <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                    </svg>
                    <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                      <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                    </svg>
                  {% endif %}
                      
                  
                  {% if i.average == 4 %}
                  <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                  </svg>
                  <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                  </svg>
                  <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                  </svg>
                  <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                  </svg>
                  {% endif %}
                  
                  {% if i.average == 5 %}
                  <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                  </svg>
                  <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                  </svg>
                  <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                  </svg>
                  <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                  </svg>
                  <svg class="bi bi-star-fill" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFCC00" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"></path>
                  </svg>
                  {% endif %}
                        
                </div>
                <div class="col-4 col-sm-2 text-end">
                  <h5 class="mb-0 font-base fw-bold">{{i.price}}</h5>
                </div>
              </div>
            </div>
          </div>
          <div class="accordion-collapse collapse shadow-lg show" id="collapse1" aria-labelledby="heading1" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <div class="row justify-content-center-center">
                <div class="col-12 col-sm-2"><a href="http://127.0.0.1:8888/book/{{i.id}}/{{i.name}}/"><img class="img-fluid d-block mx-auto mx-sm-0" src="{{ i.image.url }}" style="border-radius: 5px ;box-shadow: 5px 5px 10px gray;" width="130" alt="..." /></a></div>
                <div class="col-12 col-sm-9 mt-4 mt-sm-0 d-sm-block d-flex flex-column">
                  <ul>
                    <li class="fw-semi-bold text-black" style="direction: rtl; text-align: right;">نسخه های به فروش رفته:{{i.num_sold}}</li>
                  </ul>
                  <p style="direction: rtl; text-align: right;">{{ i.description|truncatechars_html:200 }}<button type="button" class="btn btn-link px-0 font-base"> بیشتر بخوانید </button> </p><a href="!#"><img class="my-1" src="{% static 'sevi/public/assets/img/gallery/amazon.png' %}" width="110" alt="" /></a>
                </div>
              </div>
            </div>
          </div>
        </div>
  {% endif %}
{% endfor %}
<!-- پایان بهترین کتاب-->

project/templates/component/book-shower.html
<br>
<div class="container" style="direction: rtl;">
    <div class="row">
        <div class="col-12" >
            <div class="d-flex flex-row justify-content-start flex-nowrap overflow-auto col-12 mr-auto ml-auto amir">
                
                {% for i in ii %}
                    <div class="col-md-2 col-sm-3  col-6 amirhossein" style="background-color: blueviolet; margin-top: 10px; margin-bottom: 10px; margin-left: 5px; margin-right: 5px;"><a href="http://127.0.0.1:8888/book/{{i.id}}/{{i.name}}/"><img src="{{ i.image.url }}"></a></div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

project/templates/component/buy_detail.html
{% extends 'component/user.html' %}


{% block main %}
<h1>لیست خرید ها</h1>
<hr style="width: 50%;">
<h4>جمع کل: {{ price }} تومان</h4>
<hr>

<h4>تعدا کل ایتم های خریداری شده : {{ counter }}</h4>
<hr>
<br>
<table class="table table-striped" style="margin-top: 20px;">
    <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">تاریخ</th>
            <th scope="col">قیمت</th>
            <th scope="col">نام کتاب</th>
        </tr>
    </thead>
    <tbody>

        {% for i in user %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ i.data_buy }}</td>
            <td>{{ i.price }}</td>
            <td>{{ i.book_name }}</td>
        </tr>
        {% endfor %}
{% endblock main %}

project/templates/component/my-book.html
{% extends 'component/user.html' %}


{% block main %}
<div class="alert alert-warning" role="alert">
    <h1>کتاب های خرید شده</h1>
</div>

{% for i in data %}

{% for ii in data2 %}
    {% if i.id == ii.book_id %}
    <div class="card mb-3"
    style="max-width: 540px; float: {% cycle 'right' 'left' %}; direction: {% cycle 'rtl' 'ltr' %};">
    <div class="row no-gutters">
        <div class="col-md-4 col-5">
                    <a href="http://127.0.0.1:8888/book/{{ i.id }}/{{ i.name }}">
                        <img src="{{ i.image.url }}" class="card-img" alt="...">
                    </a>
                </div>
                <div class="col-md-8 col-7">
                    <div class="card-body">
                        <h5 class="card-title">{{ i.name }}</h5>
                        <p class="card-text">{{ i.description|truncatechars:128 }}</p>
                        <a href="#"><button type="button" class="btn btn-outline-warning">مشاهده کتاب</button></a>
                        <p class="card-text"><small class="text-muted">{{ ii.data_buy }}</small></p>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endfor %}
    
{% endfor %}

{% endblock main %}

project/templates/component/nav.html
{% load static %}
<nav style="font-family: Vazir; font-weight: bold;" class="navbar navbar-expand-lg navbar-light fixed-top py-3 backdrop"
    data-navbar-on-scroll="data-navbar-on-scroll">
    <div class="container"><a class="navbar-brand d-flex align-items-center fw-semi-bold fs-3" href="#"> <img
                class="me-3" src="{% static i %}" alt="" />
            <div class="text-primary font-base">Sevi</div>
        </a>
        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto pt-2 pt-lg-0 font-base" style="font-family: Vazir;">

                <li class="nav-item"><a class="nav-link fw-medium active" aria-current="page" href="#">خانه</a></li>
                <li class="nav-item"><a class="nav-link " href="#books">پرفروش </a></li>
                <li class="nav-item"><a class="nav-link" href="#libraries">کتابخانه</a></li>


                {% if request.user.is_authenticated != True %}

                <form class="ps-lg-5" action="{% url 'authentication:login' %}" style="font-family: Vazir;">
                    <button class="btn btn-lg btn-primary rounded-pill bg-gradient font-base order-0" type="submit"
                        style="font-family: Arial, Helvetica, sans-serif; font-weight: bolder;">ورود</button>
                </form>
                {% else %}
                <li class="nav-item dropdown">
                    <button id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                        class="btn btn-lg btn-primary nav-link dropdown-toggle rounded-pill bg-gradient font-base order-0"
                        style="font-family: Vazir; color: #fdc800;" type="submit">
                        {{ user.name }}<img src="{{ user.profile_image.url }}" alt="" width="50px" height="50px"
                            style="border-radius: 50%; margin-top: 0;">
                    </button>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="text-align: right;">
                        <a class="dropdown-item" href="{% url 'profile' %}">ویرایش پروفایل <i class="fa fa-user-md"
                                aria-hidden="true"></i></a>
                        <a class="dropdown-item" href="{% url 'list' %}">اطلاعات خرید <i class="fa fa-credit-card-alt"
                                aria-hidden="true"></i></a>
                        <a class="dropdown-item" href="{% url 'my-book' %}">کتابخانه من <i class="fa fa-book"
                                aria-hidden="true"></i></a>
                        <a class="dropdown-item" href="{% url 'pin' %}">کتاب های نشان شده <i class="fa fa-bookmark-o"
                                aria-hidden="true"></i></a>
                        <a class="dropdown-item" href="{% url 'shop' %}">
                            <span class="fa-stack">
                                <!-- The icon that will wrap the number -->
                                <span class="fa fa-circle-o fa-stack-2x" style="color: #fdc800;"></span>
                                <!-- a strong element with the custom content, in this case a number -->
                                <strong class="fa-stack-1x" style="color: blue;">
                                    {{ x }}
                                </strong>
                            </span>
                            سبد خرید <i class="fa fa-shopping-basket" aria-hidden="true"></i></a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'authentication:logout' %}"> خروج از حساب <i
                                class="fa fa-sign-out" aria-hidden="true"></i></a>
                    </div>
                </li>
            </ul>
            {% endif %}

        </div>
    </div>
</nav>

project/templates/component/nav2.html
<nav class="navbar navbar-expand-lg navbar-light nav"
  style="background-color: rgba(0, 0, 0, 0.5); border-radius: 0px 0px 10px 10px;">
  <a class="navbar-brand" href="#">Sevi</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav" style="padding: 0;">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}" style="color: #fdc800;"><i class="fa fa-home"
            aria-hidden="true" style="font-size: 25px;"></i>خانه <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="color: #fdc800;"><i class="fa fa-list" aria-hidden="true" style="font-size: 25px;"></i> دسته بندی</a>
      </li>

      {% if request.user.is_authenticated == True %}
      <div
        style="background-image: url('{{ user.profile_image.url }}'); color: blue; width: 50px; height: 50px; border-radius: 50%; background-repeat: round;">
      </div>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" style="color: #fdc800; text-transform: uppercase;" href="#"
          id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.name }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="text-align: right; direction: ltr;">
          <a class="dropdown-item" href="{% url 'profile' %}">ویرایش پروفایل <i class="fa fa-user-md"
              aria-hidden="true"></i></a>
          <a class="dropdown-item" href="{% url 'list' %}">اطلاعات خرید <i class="fa fa-credit-card-alt"
              aria-hidden="true"></i></a>
          <a class="dropdown-item" href="{% url 'my-book' %}">کتابخانه من <i class="fa fa-book"
              aria-hidden="true"></i></a>
          <a class="dropdown-item" href="{% url 'pin' %}">کتاب های نشان شده <i class="fa fa-bookmark-o"
              aria-hidden="true"></i></a>
          <a class="dropdown-item" href="{% url 'shop' %}">
            <span class="fa-stack">
              <!-- The icon that will wrap the number -->
              <span class="fa fa-circle-o fa-stack-2x" style="color: #fdc800;"></span>
              <!-- a strong element with the custom content, in this case a number -->
              <strong class="fa-stack-1x" style="color: blue;">
                {{ x }}
              </strong>
            </span>
            سبد خرید <i class="fa fa-shopping-basket" aria-hidden="true"></i></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'authentication:logout' %}"> خروج از حساب <i class="fa fa-sign-out"
              aria-hidden="true"></i></a>
        </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'authentication:login' %}" style="color: #fdc800;"><i class="fa fa-sign-in"
            aria-hidden="true"></i>ورود</a>
      </li>
      {% endif %}


    </ul>

    <form class="form-inline my-2 my-lg-0 mr-auto" action="{% url 'search' %}">
      <input class="form-control mr-sm-2" type="search" style="border: 0; margin-left: 5px; font-size: smaller;"
        placeholder="نام کتاب نام نویسنده نام انتشارات و..." aria-label="Search" name="search">
      {% csrf_token %}
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit" formmethod="POST"><i class="fa fa-search"
          aria-hidden="true"></i></button>
    </form>

  </div>
</nav>

project/templates/component/opinion.html
<div class="stars col-sm-6 col-12 mr-auto ml-auto">
    <form>
        <div class="mr-auto ml-auto" >
            <input class="star star-5" id="star-5" type="radio" name="star5" />
            <label class="star star-5" for="star-5"></label>
            <input class="star star-4" id="star-4" type="radio" name="star4" />
            <label class="star star-4" for="star-4"></label>
            <input class="star star-3" id="star-3" type="radio" name="star3" />
            <label class="star star-3" for="star-3"></label>
            <input class="star star-2" id="star-2" type="radio" name="star2" />
            <label class="star star-2" for="star-2"></label>
            <input class="star star-1" id="star-1" type="radio" name="star1" />
            <label class="star star-1" for="star-1"></label>
        </div>

        <br>
        <div class="form-group">
            <textarea class="form-control" id="exampleFormControlTextarea1" placeholder="نظر خود را وارد کنید" rows="3"
                name="opi">{{ ii }}</textarea>
        </div>
        {% csrf_token %}
        <div class="mr-auto ml-auto">
            <input class="btn btn-primary mr-auto ml-auto" style="margin: auto; position: relative;" type="submit"
                value="ارسال" formmethod="POST">
        </div>

    </form>
</div>

project/templates/component/table2.html
<div class="col-lg-3 mr-auto ml-auto " style="padding: 10px;  float: right;">
    <ul class="list-group col-12 list" style="padding: 0;">

        <a href="{% url 'home' %}">
            <li class="list-group-item li2"><i class="fa fa-home amir-fa" aria-hidden="true"></i>خانه</li>
        </a>
        <a href="{% url 'profile' %}">
            <li class="list-group-item li2"><i class="fa fa-cogs amir-fa" aria-hidden="true"></i>ویرایش پروفایل</li>
        </a>
        <a href="{% url 'list' %}">
            <li class="list-group-item li2"><i class="fa fa-info-circle amir-fa" aria-hidden="true"></i>اطلاعات خرید</li>
        </a>
        <a href="{% url 'my-book' %}">
            <li class="list-group-item"><i class="fa fa-book amir-fa" aria-hidden="true"></i>کتابخانه من</li>
        </a>
        <a href="{% url 'pin' %}">
            <li class="list-group-item li2"><i class="fa fa-bookmark-o amir-fa" aria-hidden="true"></i>کتاب های نشان شده
            </li>
        </a>
        <a href="{% url 'shop' %}">
            <li class="list-group-item li2"><i class="fa fa-shopping-bag amir-fa" aria-hidden="true"></i>سبد خرید</li>
        </a>
    </ul>
</div>